### ISSUE TITLE
AST output

### ISSUE THREAD

**Issue by hudsonansley** [fdecampredon/as3ToTypescript#2]
Does this use AST as an intermediary step in the translation? If so, could it optionally save that AST output? (not so much an issue as a request)

**Comment by fdecampredon** [comment]
```
var AS3Parser = require('as3-to-typescript').Parser;

var parser = new AS3Parser();

var ast = parser.buildAst(path.basename(file), content);
```

is it enough for you ?

**Comment by hudsonansley** [comment]
cool, thanks!
